# Generated by Django 4.2.7 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_securityevent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Admin'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('client', 'Client')], default='operator', max_length=20),
        ),
    ]
