# Generated by Django 4.2.7 on 2026-03-03 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('auto_logout_minutes', models.PositiveIntegerField(default=30, help_text='Auto logout after this many minutes of inactivity.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_session_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_settings',
            },
        ),
    ]
