# Generated by Django 4.2.7 on 2026-03-07 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_failed_attempts_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsetting',
            name='password_expiry_days',
            field=models.PositiveIntegerField(blank=True, default=90, help_text='Force password change after this many days. Null/blank means no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User password history',
                'verbose_name_plural': 'User password histories',
                'db_table': 'user_password_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
