# Generated by Django 4.2.7 on 2026-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_role_relabel_client_to_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('manual_login', 'Manual Login'), ('manual_logout', 'Manual Logout'), ('auto_logout', 'Auto Logout'), ('user_created', 'User Created'), ('password_changed', 'Password Changed'), ('user_locked', 'User Locked'), ('user_unlocked', 'User Unlocked')], max_length=32),
        ),
    ]
