# Generated by Django 4.2.7 on 2026-04-04 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipment_secondary_approval_flow'),
        ('accounts', '0015_alter_useractivitylog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='equipment.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='equipment.equipment'),
        ),
    ]
