# Generated by Django 4.2.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_user_department_equipment_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivitylog",
            name="attempted_email",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email attempted when no user row is linked (unknown user) or for cross-reference.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("manual_login", "Manual Login"),
                    ("manual_logout", "Manual Logout"),
                    ("auto_logout", "Auto Logout"),
                    ("login_failed_blank_email", "Login Failed — Blank Email"),
                    ("login_failed_blank_password", "Login Failed — Blank Password"),
                    ("login_failed_invalid_password", "Login Failed — Invalid Password"),
                    ("login_failed_unknown_email", "Login Failed — Unknown Email"),
                    ("login_failed_account_locked", "Login Failed — Account Locked"),
                    ("login_failed_inactive_user", "Login Failed — Inactive User"),
                    ("user_created", "User Created"),
                    ("password_changed", "Password Changed"),
                    ("user_locked", "User Locked"),
                    ("user_unlocked", "User Unlocked"),
                ],
                max_length=32,
            ),
        ),
    ]
