# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0018_user_scoped_departments_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivitylog",
            name="detail",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional human-readable or JSON context (e.g. role or scope change).",
            ),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action (e.g. admin editing another user).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_user_activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("manual_login", "Manual Login"),
                    ("manual_logout", "Manual Logout"),
                    ("auto_logout", "Auto Logout"),
                    ("login_failed_blank_email", "Login Failed — Blank Email"),
                    ("login_failed_blank_password", "Login Failed — Blank Password"),
                    ("login_failed_invalid_password", "Login Failed — Invalid Password"),
                    ("login_failed_unknown_email", "Login Failed — Unknown Email"),
                    ("login_failed_account_locked", "Login Failed — Account Locked"),
                    ("login_failed_inactive_user", "Login Failed — Inactive User"),
                    ("user_created", "User Created"),
                    ("password_changed", "Password Changed"),
                    ("user_locked", "User Locked"),
                    ("user_unlocked", "User Unlocked"),
                    ("role_changed", "Role Changed"),
                    ("access_scope_changed", "Access Scope Changed"),
                    ("user_groups_changed", "User Groups Changed"),
                ],
                max_length=40,
            ),
        ),
    ]
