# Generated by Django 4.2.7 on 2026-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_useractivitylog_actor_detail_scope_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('manual_login', 'Manual Login'), ('manual_logout', 'Manual Logout'), ('auto_logout', 'Auto Logout'), ('login_failed_blank_email', 'Login Failed — Blank Email'), ('login_failed_blank_password', 'Login Failed — Blank Password'), ('login_failed_invalid_password', 'Login Failed — Invalid Password'), ('login_failed_unknown_email', 'Login Failed — Unknown Email'), ('login_failed_account_locked', 'Login Failed — Account Locked'), ('login_failed_inactive_user', 'Login Failed — Inactive User'), ('user_created', 'User Created'), ('password_changed', 'Password Changed'), ('user_locked', 'User Locked'), ('user_unlocked', 'User Unlocked'), ('role_changed', 'Role Changed'), ('access_scope_changed', 'Access Scope Changed')], max_length=40),
        ),
    ]
