# Generated by Django 4.2.7 on 2026-03-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('limit_update', 'Limit Update'), ('config_update', 'Configuration Update'), ('log_update', 'Log Update')], max_length=64),
        ),
    ]
