# Generated by Django 4.2.7 on 2026-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('limit_update', 'Limit Update'), ('config_update', 'Configuration Update'), ('log_update', 'Log Update'), ('log_correction', 'Log Correction')], max_length=64),
        ),
    ]
