# Generated by Django 4.2.7 on 2026-03-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('utility', 'E Log Book'), ('chemical', 'Chemical Prep'), ('validation', 'HVAC Validation'), ('filter_register', 'Filter Register'), ('air_velocity', 'Air Velocity Test'), ('filter_integrity', 'Filter Integrity Test'), ('recovery', 'Recovery Test'), ('differential_pressure', 'Differential Pressure Test'), ('nvpc', 'NVPC Test')], max_length=50),
        ),
    ]
