# Generated by Django 4.2.7 on 2026-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualChemicalConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('chemical_kg', models.FloatField(blank=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manual_chemical_consumption',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ManualChillerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('power_kwh', models.FloatField(blank=True, default=0)),
                ('water_ct1_l', models.FloatField(blank=True, default=0)),
                ('water_ct2_l', models.FloatField(blank=True, default=0)),
                ('water_ct3_l', models.FloatField(blank=True, default=0)),
                ('chemical_ct1_kg', models.FloatField(blank=True, default=0)),
                ('chemical_ct2_kg', models.FloatField(blank=True, default=0)),
                ('chemical_ct3_kg', models.FloatField(blank=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manual_chiller_consumption',
                'ordering': ['equipment_id', '-date'],
                'unique_together': {('equipment_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ManualBoilerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('power_kwh', models.FloatField(blank=True, default=0)),
                ('water_l', models.FloatField(blank=True, default=0)),
                ('chemical_kg', models.FloatField(blank=True, default=0)),
                ('diesel_l', models.FloatField(blank=True, default=0)),
                ('furnace_oil_l', models.FloatField(blank=True, default=0)),
                ('brigade_kg', models.FloatField(blank=True, default=0)),
                ('steam_kg_hr', models.FloatField(blank=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manual_boiler_consumption',
                'ordering': ['equipment_id', '-date'],
                'unique_together': {('equipment_id', 'date')},
            },
        ),
    ]
