# Generated by Django 4.2.7 on 2026-03-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_alter_auditevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingSlotsSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("log_type", models.CharField(db_index=True, max_length=32)),
                ("date_from", models.DateField(db_index=True)),
                ("date_to", models.DateField(db_index=True)),
                ("day_count", models.PositiveIntegerField(default=1)),
                ("total_missing_slots", models.PositiveIntegerField(default=0)),
                ("payload", models.JSONField()),
                ("filters", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missing_slots_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "missing_slots_snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="missingslotssnapshot",
            index=models.Index(fields=["log_type", "date_from", "date_to"], name="missing_slo_log_typ_f4f34e_idx"),
        ),
        migrations.AddIndex(
            model_name="missingslotssnapshot",
            index=models.Index(fields=["created_at"], name="missing_slo_created_c88bc2_idx"),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("limit_update", "Limit Update"),
                    ("config_update", "Configuration Update"),
                    ("log_update", "Log Update"),
                    ("log_correction", "Log Correction"),
                    ("log_created", "Log Created"),
                    ("log_deleted", "Log Deleted"),
                    ("entity_created", "Entity Created"),
                    ("entity_updated", "Entity Updated"),
                    ("entity_deleted", "Entity Deleted"),
                    ("entity_approved", "Entity Approved"),
                    ("entity_rejected", "Entity Rejected"),
                    ("consumption_updated", "Consumption Updated"),
                    ("user_created", "User Created"),
                    ("password_changed", "Password Changed"),
                    ("user_locked", "User Locked"),
                    ("user_unlocked", "User Unlocked"),
                    ("missing_slots_snapshot", "Missing Slots Snapshot"),
                ],
                max_length=64,
            ),
        ),
    ]
