# Generated by Django 4.2.7 on 2026-03-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_missingslotssnapshot_and_auditevent_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='missingslotssnapshot',
            new_name='missing_slo_log_typ_075164_idx',
            old_name='missing_slo_log_typ_f4f34e_idx',
        ),
        migrations.RenameIndex(
            model_name='missingslotssnapshot',
            new_name='missing_slo_created_f4055a_idx',
            old_name='missing_slo_created_c88bc2_idx',
        ),
    ]
