# Generated by Django 4.2.7 on 2026-04-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auditevent_query_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_timesta_3a84f9_idx',
            old_name='reports_aud_timestam_3321fd_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_event_t_7de374_idx',
            old_name='reports_aud_event_t_9d830f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_object__2836da_idx',
            old_name='reports_aud_object__6f3886_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_object__543ab2_idx',
            old_name='reports_aud_object__bcfc41_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_user_id_36e2e1_idx',
            old_name='reports_aud_user_id_61f422_idx',
        ),
    ]
