# Generated by Django 4.2.7 on 2026-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_rename_reports_aud_timestam_3321fd_idx_audit_event_timesta_3a84f9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('limit_update', 'Limit Update'), ('config_update', 'Configuration Update'), ('log_update', 'Log Update'), ('log_correction', 'Log Correction'), ('log_created', 'Log Created'), ('log_deleted', 'Log Deleted'), ('log_approved', 'Log Approved'), ('log_rejected', 'Log Rejected'), ('entity_created', 'Entity Created'), ('entity_updated', 'Entity Updated'), ('entity_deleted', 'Entity Deleted'), ('entity_approved', 'Entity Approved'), ('entity_rejected', 'Entity Rejected'), ('consumption_updated', 'Consumption Updated'), ('user_created', 'User Created'), ('password_changed', 'Password Changed'), ('user_locked', 'User Locked'), ('user_unlocked', 'User Unlocked'), ('missing_slots_snapshot', 'Missing Slots')], max_length=64),
        ),
    ]
