# Generated by Django 4.2.7 on 2026-03-05 08:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(db_index=True, default='svu-enterprises', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(db_index=True, default='svu-enterprises', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'db_table': 'equipment_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(db_index=True, help_text='Unique equipment identifier used in log entries.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.CharField(blank=True, help_text='Enter numeric value followed by optional unit, e.g. "1000 TR".', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Capacity must start with a number, e.g. "1000 TR" or "5 TPH".', regex='^\\d+(\\.\\d+)?(\\s*\\w.*)?$')])),
                ('site_id', models.CharField(blank=True, help_text='Optional site identifier, for alignment with other logs.', max_length=100, null=True)),
                ('client_id', models.CharField(db_index=True, default='svu-enterprises', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipmentcategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.department')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'ordering': ['equipment_number'],
            },
        ),
    ]
