# Generated by Django 4.2.7 on 2026-02-27 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillerlog',
            name='avg_motor_current',
            field=models.FloatField(blank=True, help_text='Average motor current (A)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='chilled_water_pump_status',
            field=models.CharField(blank=True, help_text='Chilled water pump 1/2 status (On/Off)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='chiller_control_signal',
            field=models.FloatField(blank=True, help_text='Chiller control signal (%)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='compressor_running_time_min',
            field=models.FloatField(blank=True, help_text='Compressor running time (minutes)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cond_approach_temp',
            field=models.FloatField(blank=True, help_text='Cond approach temperature', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cond_entering_water_temp',
            field=models.FloatField(blank=True, help_text='Cond entering water temperature (NMT 35 °C)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cond_leaving_water_temp',
            field=models.FloatField(blank=True, help_text='Cond leaving water temperature (NMT 40 °C)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cond_water_inlet_pressure',
            field=models.FloatField(blank=True, help_text='Cond water inlet pressure (e.g. NLT 1.5 kg/cm²)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cond_water_outlet_pressure',
            field=models.FloatField(blank=True, help_text='Cond water outlet pressure (e.g. NLT 1.0 kg/cm²)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cooling_tower_blowoff_valve_status',
            field=models.CharField(blank=True, help_text='Cooling tower blow off valve status (Open/Close)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cooling_tower_chemical_name',
            field=models.CharField(blank=True, help_text='Cooling tower chemical name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cooling_tower_chemical_qty_per_day',
            field=models.FloatField(blank=True, help_text='Cooling tower chemical quantity added per day', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cooling_tower_fan_status',
            field=models.CharField(blank=True, help_text='Cooling tower fan 1/2/3 status (On/Off)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='cooling_tower_pump_status',
            field=models.CharField(blank=True, help_text='Cooling tower pump 1/2 status (On/Off)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='evap_approach_temp',
            field=models.FloatField(blank=True, help_text='Evap approach temperature (NMT 4 °C)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='evap_entering_water_temp',
            field=models.FloatField(blank=True, help_text='Evap entering water temperature (NMT 18 °C)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='evap_leaving_water_temp',
            field=models.FloatField(blank=True, help_text='Evap leaving water temperature (e.g. 13 °C)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='evap_water_inlet_pressure',
            field=models.FloatField(blank=True, help_text='Evap water inlet pressure (e.g. NLT 2.5 kg/cm²)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='evap_water_outlet_pressure',
            field=models.FloatField(blank=True, help_text='Evap water outlet pressure', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='operator_sign',
            field=models.CharField(blank=True, help_text='Operator Sign & Date', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='recording_frequency',
            field=models.CharField(blank=True, help_text='Recording frequency (e.g. Once in 4 hours)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='starter_energy_kwh',
            field=models.FloatField(blank=True, help_text='Starter energy consumption (kWh)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Verified by (Sign & Date)', max_length=255, null=True),
        ),
    ]
