# Generated by Django 4.2.7 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0004_chillerequipmentstatusaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillerlog',
            name='comment',
            field=models.TextField(blank=True, help_text='Separate comment field for list view', null=True),
        ),
    ]
