# Generated by Django 4.2.7

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0009_chillerlog_corrects'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillerlog',
            name='daily_water_consumption_ct1_liters',
            field=models.FloatField(blank=True, help_text='Cooling tower 1 daily water consumption (liters)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='daily_water_consumption_ct2_liters',
            field=models.FloatField(blank=True, help_text='Cooling tower 2 daily water consumption (liters)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='daily_water_consumption_ct3_liters',
            field=models.FloatField(blank=True, help_text='Cooling tower 3 daily water consumption (liters)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='ChillerEquipmentLimit',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('equipment_id', models.CharField(db_index=True, help_text='Chiller equipment identifier (e.g. equipment_number)', max_length=100, unique=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('daily_power_limit_kw', models.FloatField(blank=True, help_text='Daily power consumption limit (kW)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_water_ct1_liters', models.FloatField(blank=True, help_text='Cooling tower 1 daily water consumption limit (liters)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_water_ct2_liters', models.FloatField(blank=True, help_text='Cooling tower 2 daily water consumption limit (liters)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_water_ct3_liters', models.FloatField(blank=True, help_text='Cooling tower 3 daily water consumption limit (liters)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_chemical_ct1_kg', models.FloatField(blank=True, help_text='Cooling tower 1 daily chemical consumption limit (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_chemical_ct2_kg', models.FloatField(blank=True, help_text='Cooling tower 2 daily chemical consumption limit (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_chemical_ct3_kg', models.FloatField(blank=True, help_text='Cooling tower 3 daily chemical consumption limit (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chiller Equipment Limit',
                'verbose_name_plural': 'Chiller Equipment Limits',
                'db_table': 'chiller_equipment_limits',
                'ordering': ['equipment_id'],
            },
        ),
    ]
