# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('chiller_logs', '0010_chillerequipmentlimit_and_water_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChillerLogRelatedEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chiller_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_equipment', to='chiller_logs.chillerlog')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiller_log_relations', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Chiller Log Related Equipment',
                'verbose_name_plural': 'Chiller Log Related Equipment',
                'db_table': 'chiller_log_related_equipment',
                'ordering': ['chiller_log', 'order', 'equipment_id'],
                'unique_together': {('chiller_log', 'equipment')},
            },
        ),
    ]
