# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chiller_logs', '0011_chillerlogrelatedequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolingTowerChemicalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('equipment_id', models.CharField(db_index=True, help_text='Chiller equipment identifier', max_length=100)),
                ('tower_slot', models.CharField(choices=[('CT-1', 'Cooling Tower 1'), ('CT-2', 'Cooling Tower 2'), ('CT-3', 'Cooling Tower 3')], db_index=True, max_length=10)),
                ('chemical_name', models.CharField(max_length=200)),
                ('quantity_kg', models.FloatField(help_text='Quantity (kg)', validators=[django.core.validators.MinValueValidator(0)])),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ct_chemical_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cooling Tower Chemical Log',
                'verbose_name_plural': 'Cooling Tower Chemical Logs',
                'db_table': 'cooling_tower_chemical_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
