# Generated by Django 4.2.7 on 2026-03-08 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0012_coolingtowerchemicallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chillerequipmentlimit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
