# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0013_alter_chillerequipmentlimit_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChillerLogRelatedEquipment',
        ),
    ]
