# Generated by Django 4.2.7 on 2026-03-08 14:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0014_remove_chillerlogrelatedequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChillerDashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projected_power_kwh_month', models.FloatField(blank=True, help_text='Projected power consumption per month (kWh) for comparison', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_rate_rs_per_kwh', models.FloatField(blank=True, help_text='Electricity rate (Rs per kWh) for cost calculation', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chiller Dashboard Config',
                'verbose_name_plural': 'Chiller Dashboard Config',
                'db_table': 'chiller_dashboard_config',
            },
        ),
    ]
