# Generated by Cursor on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chiller_logs", "0015_chiller_dashboard_config"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoolingTowerChemicalLog",
        ),
    ]

