# Generated by Django 4.2.7 on 2026-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0020_remove_chillerlog_cooling_tower_chemical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillerequipmentlimit',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Date from which this limit applies. Leave blank to apply to all dates.', null=True),
        ),
    ]
