# Generated by Django 4.2.7 on 2026-03-15 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0021_chillerequipmentlimit_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillerequipmentlimit',
            name='projected_power_kwh_month',
            field=models.FloatField(blank=True, help_text='Projected power consumption per month (kWh) for dashboard comparison', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
