# Generated by Django 4.2.7 on 2026-03-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0022_chillerequipmentlimit_projected_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chillerequipmentlimit',
            name='projected_power_kwh_month',
        ),
    ]
