# Generated by Django 4.2.7 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerlog',
            name='comment',
            field=models.TextField(blank=True, help_text='Separate comment field for list view', null=True),
        ),
    ]
