# Generated by Django 4.2.7 on 2026-03-02 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_logs', '0003_alter_boilerlog_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerlog',
            name='boiler_steam_pressure',
            field=models.FloatField(blank=True, help_text='Boiler steam pressure NLT 5 kg/cm²', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='burner_heater_temp',
            field=models.FloatField(blank=True, help_text='Burner heater temp 120±10°C', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='burner_oil_pressure',
            field=models.FloatField(blank=True, help_text='Burner oil pressure 18-25 kg/cm²', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='feed_water_hardness_ppm',
            field=models.FloatField(blank=True, help_text='Feed water hardness NMT 5 PPM', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='feed_water_tank_level',
            field=models.FloatField(blank=True, help_text='Feed water tank level (KL)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='feed_water_tds_ppm',
            field=models.FloatField(blank=True, help_text='Feed water TDS NMT 700 PPM', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='fo_hsd_ng_consumption',
            field=models.FloatField(blank=True, help_text='FO/HSD/NG consumption ending of shift (Ltr)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='fo_hsd_ng_day_tank_level',
            field=models.FloatField(blank=True, help_text='FO/HSD/NG day tank level (Ltr)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='fo_pre_heater_temp',
            field=models.FloatField(blank=True, help_text='FO pre heater temp 60-70°C', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='manual_blowdown_time',
            field=models.CharField(blank=True, help_text='Manual blow down time e.g. 14:30', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='mobrey_functioning',
            field=models.CharField(blank=True, help_text='Mobrey functioning Yes/No', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='stack_temperature',
            field=models.FloatField(blank=True, help_text='Stack temperature 180-250°C', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='steam_pressure_after_prv',
            field=models.FloatField(blank=True, help_text='Steam pressure after PRV NLT 5 kg/cm²', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
