# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('boiler_logs', '0007_boilerlog_corrects'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerlog',
            name='diesel_stock_liters',
            field=models.FloatField(blank=True, help_text='Diesel stock (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='diesel_cost_rupees',
            field=models.FloatField(blank=True, help_text='Diesel cost (Rs)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='furnace_oil_stock_liters',
            field=models.FloatField(blank=True, help_text='Furnace oil stock (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='furnace_oil_cost_rupees',
            field=models.FloatField(blank=True, help_text='Furnace oil cost (Rs)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='brigade_stock_kg',
            field=models.FloatField(blank=True, help_text='Brigade stock (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='brigade_cost_rupees',
            field=models.FloatField(blank=True, help_text='Brigade cost (Rs)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='daily_power_consumption_kwh',
            field=models.FloatField(blank=True, help_text='Daily power consumption (kWh)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='daily_water_consumption_liters',
            field=models.FloatField(blank=True, help_text='Daily water consumption (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='daily_chemical_consumption_kg',
            field=models.FloatField(blank=True, help_text='Daily chemical consumption (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='BoilerEquipmentLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_id', models.CharField(db_index=True, help_text='Boiler equipment identifier', max_length=100, unique=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('daily_power_limit_kw', models.FloatField(blank=True, help_text='Daily power consumption limit (kW)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_water_limit_liters', models.FloatField(blank=True, help_text='Daily water consumption limit (liters)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_chemical_limit_kg', models.FloatField(blank=True, help_text='Daily chemical consumption limit (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boiler Equipment Limit',
                'verbose_name_plural': 'Boiler Equipment Limits',
                'db_table': 'boiler_equipment_limits',
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='BoilerLogRelatedEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boiler_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_equipment', to='boiler_logs.boilerlog')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boiler_log_relations', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Boiler Log Related Equipment',
                'verbose_name_plural': 'Boiler Log Related Equipment',
                'db_table': 'boiler_log_related_equipment',
                'ordering': ['boiler_log', 'order', 'equipment_id'],
                'unique_together': {('boiler_log', 'equipment')},
            },
        ),
    ]
