# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_logs', '0008_boiler_fuel_limits_related_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoilerLogRelatedEquipment',
        ),
    ]
