# Generated by Django 4.2.7 on 2026-03-08 15:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_logs', '0009_remove_boilerlogrelatedequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerDashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projected_power_kwh_month', models.FloatField(blank=True, help_text='Projected power consumption per month (kWh) for comparison', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('projected_oil_cost_rs_month', models.FloatField(blank=True, help_text='Projected oil cost per month (Rs) for comparison', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boiler Dashboard Config',
                'verbose_name_plural': 'Boiler Dashboard Configs',
                'db_table': 'boiler_dashboard_configs',
            },
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='brigade_rate_rs_per_kg',
            field=models.FloatField(blank=True, help_text='Brigade rate (Rs/kg)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='daily_brigade_limit_kg',
            field=models.FloatField(blank=True, help_text='Daily brigade consumption limit (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='daily_diesel_limit_liters',
            field=models.FloatField(blank=True, help_text='Daily diesel consumption limit (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='daily_furnace_oil_limit_liters',
            field=models.FloatField(blank=True, help_text='Daily furnace oil consumption limit (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='daily_steam_limit_kg_hr',
            field=models.FloatField(blank=True, help_text='Steam consumption limit (kg/hr)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='diesel_rate_rs_per_liter',
            field=models.FloatField(blank=True, help_text='Diesel rate (Rs/L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='electricity_rate_rs_per_kwh',
            field=models.FloatField(blank=True, help_text='Electricity rate (Rs/kWh)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='furnace_oil_rate_rs_per_liter',
            field=models.FloatField(blank=True, help_text='Furnace oil rate (Rs/L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='daily_brigade_consumption_kg',
            field=models.FloatField(blank=True, help_text='Daily brigade consumption (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='daily_diesel_consumption_liters',
            field=models.FloatField(blank=True, help_text='Daily diesel consumption (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='daily_furnace_oil_consumption_liters',
            field=models.FloatField(blank=True, help_text='Daily furnace oil consumption (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='boilerlog',
            name='steam_consumption_kg_hr',
            field=models.FloatField(blank=True, help_text='Steam consumption (kg/hr); if null, steam_flow_lph used as proxy', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
