# Generated by Django 4.2.7 on 2026-03-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_logs', '0012_remove_boilerlog_fuel_stock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerequipmentlimit',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Date from which this limit applies. Leave blank to apply to all dates.', null=True),
        ),
    ]
