# Generated by Django 4.2.7 on 2026-04-07 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_logs', '0014_remove_boilerlog_legacy_hourly_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerlog',
            name='steam_consumption_kg_hr',
            field=models.FloatField(blank=True, help_text='Steam consumption (kg/hr)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
