# Generated by Django 4.2.7 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0002_logbookschema_created_by_logbookroleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookroleassignment',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('supervisor', 'Supervisor'), ('manager', 'Admin'), ('super_admin', 'Super Admin'), ('client', 'Client')], max_length=20),
        ),
    ]
