# Generated by Django 4.2.7 on 2026-03-05 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_category', models.CharField(blank=True, help_text='Area category such as Production, Utility, AHU Room, etc.', max_length=100, null=True)),
                ('tag_info', models.CharField(blank=True, help_text='Optional tag information for integration with log books.', max_length=255, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filter_assignments', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Filter Assignment',
                'verbose_name_plural': 'Filter Assignments',
                'db_table': 'filter_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(db_index=True, default='svu-enterprises', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filter Category',
                'verbose_name_plural': 'Filter Categories',
                'db_table': 'filter_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilterSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('replacement', 'Replacement'), ('cleaning', 'Cleaning'), ('integrity', 'Integrity')], max_length=32)),
                ('frequency_days', models.PositiveIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='filter_master.filterassignment')),
            ],
            options={
                'verbose_name': 'Filter Schedule',
                'verbose_name_plural': 'Filter Schedules',
                'db_table': 'filter_schedules',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='FilterMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filter_id', models.CharField(editable=False, help_text='System-generated filter identifier, e.g. FMT-0001.', max_length=32, unique=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('size_l', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('micron_size', models.CharField(choices=[('0.2', '0.2 µ'), ('0.45', '0.45 µ'), ('1', '1 µ'), ('3', '3 µ'), ('5', '5 µ'), ('10', '10 µ'), ('20', '20 µ'), ('100', '100 µ')], max_length=10)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='filter_certificates/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.CharField(db_index=True, default='svu-enterprises', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_filters', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='filter_master.filtercategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filter Master',
                'verbose_name_plural': 'Filter Masters',
                'db_table': 'filter_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='filterassignment',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='filter_master.filtermaster'),
        ),
    ]
