# Generated by Django 4.2.7 on 2026-03-08 16:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filter_master', '0004_alter_filtermaster_filter_id_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projected_replacement_count_month', models.PositiveIntegerField(blank=True, help_text='Projected number of filter replacements per month for comparison', null=True)),
                ('projected_cleaning_count_month', models.PositiveIntegerField(blank=True, help_text='Projected number of filter cleanings per month for comparison', null=True)),
                ('projected_integrity_count_month', models.PositiveIntegerField(blank=True, help_text='Projected number of filter integrity activities per month for comparison', null=True)),
                ('projected_cost_rs_month', models.FloatField(blank=True, help_text='Projected filter-related cost per month (Rs) for comparison', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filter Dashboard Config',
                'verbose_name_plural': 'Filter Dashboard Config',
                'db_table': 'filter_dashboard_config',
            },
        ),
    ]
