# Generated by Django 4.2.7 on 2026-03-26 07:01

from django.db import migrations, models
import django.db.models.deletion


def _clear_category_before_equipment_fk(apps, schema_editor):
    """category_id values point at filter_categories; repointing the FK to
    equipment_categories requires matching UUIDs there. Clear so AlterField succeeds."""
    FilterMaster = apps.get_model("filter_master", "FilterMaster")
    FilterMaster.objects.filter(category_id__isnull=False).update(category_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipment_secondary_approval_flow'),
        ('filter_master', '0005_filter_dashboard_config'),
    ]

    operations = [
        # category_id may still be NOT NULL from 0001; allow NULL before we clear and repoint FK.
        migrations.RunSQL(
            "ALTER TABLE filter_master ALTER COLUMN category_id DROP NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(_clear_category_before_equipment_fk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='filtermaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='equipment.equipmentcategory'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='FilterCategory',
                ),
            ],
        ),
    ]
