# Generated by Django 4.2.7 on 2026-03-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipment_secondary_approval_flow'),
        ('filter_master', '0005_filter_dashboard_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtermaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='equipment.equipmentcategory'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='FilterCategory',
                ),
            ],
        ),
    ]
