# Generated by Django 4.2.7 on 2026-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_master', '0006_alter_filtermaster_category_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='filtermaster',
                    constraint=models.UniqueConstraint(
                        condition=models.Q(('serial_number__isnull', False), models.Q(('serial_number', ''), _negated=True)),
                        fields=('serial_number',),
                        name='uniq_filter_master_serial_number_non_empty',
                    ),
                ),
            ],
        ),
    ]
