# Generated by Django 4.2.7 on 2026-03-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter_master', '0008_filtercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtermaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='filter_master.filtercategory'),
        ),
    ]
