# Generated by Django 4.2.7 on 2026-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_master', '0009_alter_filtermaster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='active', max_length=16),
        ),
    ]
