# Generated by Django 4.2.7 on 2026-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterlog',
            name='category',
            field=models.CharField(choices=[('hvac', 'HVAC'), ('water_system', 'Water system'), ('compressed_air', 'Compressed air'), ('nitrogen_air', 'Nitrogen air'), ('utilities', 'Utilities')], max_length=32),
        ),
    ]
