# Generated by Django 4.2.7 on 2026-03-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_logs', '0002_alter_filterlog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterlog',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
