# Generated by Django 4.2.7 on 2026-03-24 10:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BriquetteLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_id', models.CharField(db_index=True, max_length=100)),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_type', models.CharField(choices=[('operation', 'Operation'), ('maintenance', 'Maintenance'), ('shutdown', 'Shutdown')], default='operation', max_length=16)),
                ('activity_from_date', models.DateField(blank=True, null=True)),
                ('activity_to_date', models.DateField(blank=True, null=True)),
                ('activity_from_time', models.TimeField(blank=True, null=True)),
                ('activity_to_time', models.TimeField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=20, null=True)),
                ('steam_pressure', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('furnace_pressure_mmwc', models.FloatField(blank=True, null=True)),
                ('id_fan_op_percent', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pa_damper_position_1', models.FloatField(blank=True, null=True)),
                ('pa_damper_position_2', models.FloatField(blank=True, null=True)),
                ('metering_screw_percent', models.FloatField(blank=True, null=True)),
                ('steam_reading_ton', models.FloatField(blank=True, null=True)),
                ('steam_flow_kg_hr', models.FloatField(blank=True, null=True)),
                ('stack_temp', models.FloatField(blank=True, null=True)),
                ('furnace_temp', models.FloatField(blank=True, null=True)),
                ('hot_air_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('feed_pump_1_2', models.CharField(blank=True, max_length=20, null=True)),
                ('operator_sign_date', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_water_ph', models.FloatField(blank=True, null=True)),
                ('feed_water_hardness_ppm', models.FloatField(blank=True, null=True)),
                ('feed_water_tds_ppm', models.FloatField(blank=True, null=True)),
                ('boiler_water_ph', models.FloatField(blank=True, null=True)),
                ('boiler_water_hardness_ppm', models.FloatField(blank=True, null=True)),
                ('boiler_water_tds_ppm', models.FloatField(blank=True, null=True)),
                ('total_steam_in_1_day', models.CharField(blank=True, max_length=50, null=True)),
                ('total_steam_flow_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_secondary_approval', 'Pending secondary approval')], default='draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('secondary_approved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_briquette_logs', to=settings.AUTH_USER_MODEL)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='briquette_logs.briquettelog')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briquette_logs', to=settings.AUTH_USER_MODEL)),
                ('secondary_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_approved_briquette_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'briquette_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
