# Generated by Django 4.2.7 on 2026-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briquette_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briquettelog',
            name='verified_sign_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
