# Generated by Django 4.2.7 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0003_remove_chemicalpreparation_feed_water_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalpreparation',
            name='comment',
            field=models.TextField(blank=True, help_text='Separate comment field for list view', null=True),
        ),
    ]
