# Generated by Django 4.2.7 on 2026-03-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0004_chemicalpreparation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalpreparation',
            name='remarks',
            field=models.TextField(blank=True, help_text='Operator remarks from entry form', null=True),
        ),
    ]
