# Generated by Django 4.2.7 on 2026-03-02 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0005_alter_chemicalpreparation_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalpreparation',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='done_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='quantity_taken',
            field=models.FloatField(blank=True, help_text='Quantity taken (L or Kg)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
