# Generated by Django 4.2.7 on 2026-03-06 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0012_chemicalpreparation_chemical_concentration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('water_system', 'Water system'), ('cooling_towers', 'Cooling towers'), ('boiler', 'Boiler')], max_length=32)),
                ('formula', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text='Optional category such as major/minor or process group.', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chemical',
                'verbose_name_plural': 'Chemicals',
                'db_table': 'chemicals',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChemicalStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_qty_kg', models.FloatField(default=0, help_text='Available quantity in kilograms.', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', help_text='Display unit for stock quantity (e.g. kg).', max_length=16)),
                ('price_per_unit', models.FloatField(blank=True, help_text='Price per unit (e.g. per kg).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('site', models.CharField(blank=True, help_text='Optional site identifier for multi-site setups.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='chemical_prep.chemical')),
            ],
            options={
                'verbose_name': 'Chemical Stock',
                'verbose_name_plural': 'Chemical Stock',
                'db_table': 'chemical_stock',
            },
        ),
    ]
