# Generated by Django 4.2.7 on 2026-03-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0014_chemicalassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemicalassignment',
            options={'ordering': ['equipment_name', 'chemical_name'], 'verbose_name': 'Chemical Assignment', 'verbose_name_plural': 'Chemical Assignments'},
        ),
        migrations.AddField(
            model_name='chemicalassignment',
            name='chemical_formula',
            field=models.CharField(blank=True, help_text='Optional formula when entered manually.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chemicalassignment',
            name='chemical_name',
            field=models.CharField(blank=True, help_text='Chemical name when entered manually (no dropdown).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalassignment',
            name='chemical',
            field=models.ForeignKey(blank=True, help_text='Optional link to chemical master; use chemical_name when entering manually.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='chemical_prep.chemical'),
        ),
    ]
