# Generated by Django 4.2.7 on 2026-03-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0015_assignment_manual_chemical_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalassignment',
            name='location',
            field=models.CharField(blank=True, help_text='Location when entered manually (e.g. Water system, Cooling towers).', max_length=64, null=True),
        ),
    ]
