# Generated by Django 4.2.7

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0016_assignment_add_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalDashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projected_consumption_kg_month', models.FloatField(blank=True, help_text='Projected chemical consumption per month (kg) for comparison', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('projected_cost_rs_month', models.FloatField(blank=True, help_text='Projected chemical cost per month (Rs) for comparison', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chemical_dashboard_config',
                'verbose_name': 'Chemical Dashboard Config',
                'verbose_name_plural': 'Chemical Dashboard Config',
            },
        ),
    ]
