# Generated by Django for Chemical Assignment approve/reject

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_existing_approved(apps, schema_editor):
    ChemicalAssignment = apps.get_model("chemical_prep", "ChemicalAssignment")
    ChemicalAssignment.objects.all().update(status="approved")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chemical_prep", "0018_activity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicalassignment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                help_text="Approval status for this assignment.",
                max_length=16,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="chemicalassignment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_chemical_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chemicalassignment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chemicalassignment",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_chemical_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chemicalassignment",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chemicalassignment",
            name="rejection_comment",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(set_existing_approved, noop),
    ]
