# Generated by Django 4.2.7 on 2026-04-02 06:32

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0019_chemicalassignment_approval'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chemicalpreparation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim(models.F('batch_no'))), condition=models.Q(('batch_no__isnull', False), models.Q(('batch_no', ''), _negated=True)), name='uniq_chemicalprep_batch_no_ci_trim'),
        ),
    ]
