# Generated by Django 4.2.7 on 2026-04-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0020_uniq_batch_no_trim_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chemicalpreparation',
            name='uniq_chemicalprep_batch_no_ci_trim',
        ),
    ]
