# Generated by Django 4.2.7 on 2026-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0022_chemicaldailylimit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chemicaldailylimit',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_from__isnull', True)), fields=('id',), name='uniq_chemical_daily_limit_default_single'),
        ),
    ]
